apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    deployment: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-worker
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      containers:
      - name: kuberos-api-server
        image: metagoto/kuberos:v0.1
        imagePullPolicy: Always
        command: ['/bin/bash']
        args: ['-c', 'celery -A settings worker -l info']
        env:
          - name: REDIS_HOST
            value: redis-service
      imagePullSecrets:
        - name: kuberos-test-repo