apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.7
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "kuberos"
            - name: POSTGRES_PASSWORD
              value: "deploy_ros2_humble"
            - name: POSTGRES_DB
              value: "kuberos_db"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume-mount
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      nodeSelector: 
        kuberos.io/kuberos: kuberos-control-plane
        # kubernetes.io/hostname: server01
      tolerations: 
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    name: postgres
